services:
  app:
    build: .
    container_name: sgi
    ports:
      - 8081:80
    volumes:
      - app_files:/var/www/html/webroot/files
      - app_uploads:/var/www/html/webroot/uploads
      - app_storage:/var/www/html/storage

volumes:
  app_files:
  app_uploads:
  app_storage:
